### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by bigsby-exe** [FCoQ/dobby#37]
Hi I have tryed to run this on both mac and PC and get an error on npm start 

The Error I get reads 

```
'nodejs' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files
rt"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! dobby@0.0.1 start: `nodejs app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dobby@0.0.1 start script 'nodejs app.js'.
npm ERR! Make sure you have the latest version of node.js and npm inst
npm ERR! If you do, this is most likely a problem with the dobby packa
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dobby
```

PC log- http://pastebin.com/JXHhWKJK

and on OSX reads 

```
sh: nodejs: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dobby@0.0.1 start: `nodejs app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the dobby@0.0.1 start script 'nodejs app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dobby package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dobby
```

OSX log-http://pastebin.com/TfnC4J9y

am I doing the install wrong or just generally being an idiot 
any help would be greatly appreciated this looks like a really cool project and I would love to use it.

**Comment by quibsorg** [comment]
Thanks for posting this issue. I believe it is happening because of the node binary being named differently on different operating systems. 

To fix on windows: Copy&paste this C:\Program Files\nodejs\node.exe executable and rename it to nodejs.exe in that same dir.

To fix on OSX: Either do the same thing as the windows fix or you can create a symlink like this. "ln -s /usr/local/bin/node /usr/local/bin/nodejs"

This is a temporary solution until one of us can update the start script, but it should be sufficient to get you started! Also please note that the "howhot" plugin is currently broken, so you'll want to disable that in your config.

**Comment by bigsby-exe** [comment]
Sweet, that got it working. Thank you so much. gonna try my hand at plugin making now haha

**Comment by quibsorg** [comment]
Good luck and let me know if I can help with anything.

**Comment by bigsby-exe** [comment]
hey @quibsorg can dobby poke or pm users I was looking to make a secret Santa plugin that poked or secretly messaged users with there secret Santa name 

Edit: ohh the Client.private_message should do it right? but how do I get it to work?

**Comment by qshane** [comment]
@bzyg7b `dobby.client` (inside of `onMessage`) will give you access to a `Client` object which has the `private_message` method on it. Currently poking is not supported but it could be added easily.

**Comment by bigsby-exe** [comment]
would this be the correct use?

```
exports.onMessage = function(msg, dobby) {
    var terms = msg.split(" ");
    var command = terms.shift();
    terms = terms.join(" ");

    if (command == '.test') {
    dobby.Client.private_message("yes")
    }
}
```

Apologies on being a bit of a noob, any and all help is very much appreciated.

**Comment by qshane** [comment]
Should be `dobby.client.private_message`.

**Comment by bigsby-exe** [comment]
Thanks for the reply but this returns 

```
TypeError: Cannot read property 'private_message' of undefined
    at Object.exports.onMessage (C:\Users\Danny\Documents\GitHub\dobby\plugins\test.js:6:21)
    at C:\Users\Danny\Documents\GitHub\dobby\plugins.js:63:9
    at Array.forEach (native)
    at Object.exports.onMessage (C:\Users\Danny\Documents\GitHub\dobby\plugins.js:61:10)
    at Object.on_channel_message (C:\Users\Danny\Documents\GitHub\dobby\app.js:197:45)
    at TeamSpeakClient.<anonymous> (C:\Users\Danny\Documents\GitHub\dobby\bot.js:84:17)
    at emitOne (events.js:77:13)
    at TeamSpeakClient.emit (events.js:169:7)
    at LineInputStream.<anonymous> (C:\Users\Danny\Documents\GitHub\dobby\node_modules\node-teamspea
k\index.js:188:10)
    at emitOne (events.js:77:13)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! dobby@0.0.1 start: `nodejs app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dobby@0.0.1 start script 'nodejs app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dobby package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dobby
npm ERR! There is likely additional logging output above.
```

when I try to run it?

**Comment by bigsby-exe** [comment]
ohh I am an idiot I needed 

```
    dobby.client_from.private_message
```
